import Head from 'next/head'
// import Image from 'next/image'
import { League_Spartan } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { VStack, Image, Box, Flex, Text } from '@chakra-ui/react'
import { getData } from '@/data/getData'
import { lowongan } from '@/types'

const league = League_Spartan({weight:['500','700'], subsets: ['latin'] })

export default function Home({data}:{data:lowongan[]}) {
  return (
    <>
      <Head>
        <title>Job Listing with Filter</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className={league.className}>
        <Box bg="brand.bg" w="100%">
          <Box  w="100%" bg="brand.darkCyan">
            <Image src="/images/bg-header-desktop.svg" w="100%" />  
          </Box>
          
          <VStack w="100vw" h={{base:"100%", sm:"100vh"}} minH="100vh" bg="brand.bg">
            {
              data.map(item =>{
                  return <Flex flexDir={{base:"column", sm:"row"}} key={item.id} bg="white">
                      <Image src={item.logo} />
                      <VStack>
                        <Text color="brand.darkCyan">{item.company}</Text>
                        <Text _hover={{color:"brand.darkCyan"}}>{item.position}</Text>
                        <Flex justifyContent="space-between" color="brand.greyCyan">
                          <Text>{item.postedAt}</Text>
                          <Text>{item.contract}</Text>
                          <Text>{item.location}</Text>
                        </Flex>
                      </VStack>
                      <Flex>
                        <Text bg="brand.bg" color="brand.darkCyan">{item.role}</Text>
                      </Flex>
                  </Flex>
              })
            }
            
          </VStack>
        </Box>
        
      </main>
    </>
  )
}

export async function getStaticProps() {
  const data = await getData();
  return {
    props: {
      data
    }
  }
}
