import Head from 'next/head'
// import Image from 'next/image'
import { League_Spartan } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { VStack, Image, Box } from '@chakra-ui/react'
import { getData } from '@/data/getData'
import { lowongan } from '@/types'

const league = League_Spartan({weight:['500','700'], subsets: ['latin'] })

export default function Home({data}:{data:lowongan[]}) {
  return (
    <>
      <Head>
        <title>Job Listing with Filter</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={league.className}>
        <Box bg="brand.bg">
          {/* <Box bgImage={{base:"/images/bg-header-mobile.svg", sm:"/images/bg-header-desktop.svg"}}
            w="100%" h="calc(0.664 * 100vw)" bgSize="contain" bgRepeat="no-repeat">
            
          </Box> */}
          <Image src="/images/bg-header-desktop.svg" />
          <VStack w="100vw" h={{base:"100%", sm:"100vh"}} minH="100vh" bg="brand.bg">

          </VStack>
        </Box>
        
      </main>
    </>
  )
}

export async function getStaticProps() {
  const data = await getData();
  return {
    props: {
      data
    }
  }
}
